core/urls.py
from django.urls import path
from .views import (HomeView,
                    ItemDetailView,
                    CheckoutView,
                    add_to_cart,
                    remove_from_cart,
                    OrderSummaryView,
                    remove_single_item_from_cart,
                    PaymentView,
                    AddCuponView,
                    RequestRefundView,
                    category_product_view
                    )

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('category/<category>/',
         category_product_view, name='category-product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-cupon/', AddCuponView.as_view(), name='add-cupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund', RequestRefundView.as_view(), name='request-refund'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.shortcuts import reverse
from django_resized import ResizedImageField
from django.db import models
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    img = ResizedImageField(size=[500, 500], crop=[
                            'middle', 'center'], upload_to='products')
    price = models.FloatField()
    description = models.TextField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    def get_absolute_category(self):
        return reverse("core:category-product", kwargs={"category": self.category})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    cupon = models.ForeignKey(
        'Cupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delicered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.cupon:
            total -= self.cupon.amount
        return total


DIVISION_CHOICES = (
    ('BAR', 'Barishal'),
    ('CHI', 'Chittagong'),
    ('DHA', 'Dhaka'),
    ('KHU', 'Khulna'),
    ('MYM', 'Mymensingh'),
    ('RAJ', 'Rajshahi'),
    ('RAN', 'Rangpur'),
    ('SYL', 'Sylhet')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    secondary_addrs = models.CharField(max_length=100)
    division = models.CharField(choices=DIVISION_CHOICES, max_length=3)
    country = CountryField(multiple=False)
    zip_code = models.CharField(max_length=6)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Cupon(models.Model):
    cupon = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.cupon


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    email = models.EmailField()
    reason = models.TextField()
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.pk}'

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


DIVISION_CHOICES = (
    ('BAR', 'Barishal'),
    ('CHI', 'Chittagong'),
    ('DHA', 'Dhaka'),
    ('KHU', 'Khulna'),
    ('MYM', 'Mymensingh'),
    ('RAJ', 'Rajshahi'),
    ('RAN', 'Rangpur'),
    ('SYL', 'Sylhet')
)

PAYMENT_CHOICES = (
    ('C', 'Credit Card'),
    ('P', 'Paypal'),
)


class CheckoutForm(forms.Form):

    # shipping ===============>

    shipping_address = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Mirpur 2'
        }
    ))
    shipping_address2 = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Love Road'
        }
    ))
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(
            attrs={
                'class': 'custom-select d-block w-100'}
        )
    )
    shipping_division = forms.ChoiceField(
        choices=DIVISION_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'custom-select d-block w-100'}
        ))
    shipping_zip = forms.CharField(
        max_length=6, widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Zip Code'
            }
        ))

    # billing ==============>

    billing_address = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Mirpur 2'
        }
    ))
    billing_address2 = forms.CharField(max_length=100, required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Love Road'
        }
    ))
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(
            attrs={
                'class': 'custom-select d-block w-100'}
        )
    )
    billing_division = forms.ChoiceField(
        choices=DIVISION_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'custom-select d-block w-100'}
        ))

    billing_zip = forms.CharField(
        max_length=6, widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Zip Code'
            }
        ))

    # checkbox ============>

    same_billing_address = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(
            attrs={
                'class': 'custom-control-input'
            }
        ))

    set_default_shipping = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(
            attrs={
                'class': 'custom-control-input'
            }
        ))
    use_default_shipping = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(
            attrs={
                'class': 'custom-control-input'
            }
        ))

    set_default_billing = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(
            attrs={
                'class': 'custom-control-input'
            }
        ))
    use_default_billing = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(
            attrs={
                'class': 'custom-control-input'
            }
        ))

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect(), choices=PAYMENT_CHOICES)


class CuponForm(forms.Form):
    cupon = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria_label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField(max_length=20)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))

templates/base.html
{% load static %}
{% load cart_tamplate_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}DJEcommerce{% endblock %}</title>
    {% block extra_head %}
    {% endblock extra_head %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  {% comment %} data table {% endcomment %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  {% comment %} Stripe JS {% endcomment %}
  {% comment %} <script src="https://js.stripe.com/v3/"></script> {% endcomment %}
</head>
<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:home' %}" target="">
        <strong class="blue-text">DJEcommerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="" target="">Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:checkout' %}"
              target="">Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}"  class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect btn btn-warning btn-sm" href="{% url 'account_logout' %}">
              <i class=""></i>
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <i class=""></i>
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <i class=""></i>
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

  {% comment %} carousel {% endcomment %}
  <header>
  {% block carousel %}
  {% endblock carousel %}
  </header>

  {% comment %} messages {% endcomment %}
    <div class="mt-2 pt-1">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}
    </div>

    

    {% block content  %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  {% comment %} stripe script {% endcomment %}
  {% comment %} <script type="text/javascript" src="{% static 'js/stripe.js' %}"></script> {% endcomment %}

  {% block extra_scripts %}
    
  {% endblock extra_scripts %}

  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

    $(document).ready(function() {
        $('#example').DataTable();
    } );

  </script>

  {% block extra_scripts_for_checkout_form %}
  {% endblock extra_scripts_for_checkout_form %}
</body>

</html>

templates/checkout.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">
          <div class="card">

            <form method="POST" class="card-body" action="">
              {% csrf_token %}

              <h3>Shipping Address</h3>

              <div class="hidable_shipping_form">
                <div class="md-form mb-5">
                  <label for="id_shipping_address" class="">Address</label>
                  {{ form.shipping_address }}
                  {% comment %} <input type="text" placeholder="Mirpur 2" id="shipping_address" name="shipping_address" class="form-control"> {% endcomment %}
                </div>

                <div class="md-form mb-5">
                  <label for="id_shipping_address2" class="">Address 2 (optional)</label>
                  {{ form.shipping_address2 }}
                  {% comment %} <input type="text" placeholder="Love Road" id="shipping_address2" name="shipping_address2" class="form-control"> {% endcomment %}
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="id_shipping_country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="id_shipping_division">Division</label>
                    {{ form.shipping_division }}
                    <div class="invalid-feedback">
                      Please provide a valid Division.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip Code</label>
                    {{ form.shipping_zip }}
                    {% comment %} <input type="text" placeholder="Zip Code" id="shipping_zip" name="shipping_zip" class="form-control"> {% endcomment %}
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  {% comment %} <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address"> {% endcomment %}
                  {{ form.same_billing_address }}
                  <label class="custom-control-label" for="id_same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  {% comment %} <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping"> {% endcomment %}
                  {{ form.set_default_shipping }}
                  <label class="custom-control-label" for="id_set_default_shipping">Save the default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                {% comment %} <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping"> {% endcomment %}
                {{ form.use_default_shipping }}
                <label class="custom-control-label" for="id_use_default_shipping">Use default shipping address: {{ default_shipping_address.secondary_addrs|truncatechars:20 }}</label>
              </div>
              {% endif %}

              <hr>
            <div class="hidable_same_billing_form">
              <h3>Billing Address</h3>
              
              <div class="hidable_billing_form">
                <div class="md-form mb-5">
                  <label for="id_billing_address" class="">Address</label>
                  {{ form.billing_address }}
                  {% comment %} <input type="text" placeholder="Mirpur 2" id="billing_address" name="billing_address" class="form-control"> {% endcomment %}
                </div>

                <div class="md-form mb-5">
                  <label for="id_billing_address2" class="">Address 2 (optional)</label>
                  {{ form.billing_address2 }}
                  {% comment %} <input type="text" placeholder="Love Road" id="billing_address2" name="billing_address2" class="form-control"> {% endcomment %}
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="id_billing_country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="id_billing_division">Division</label>
                    {{ form.billing_division }}
                    <div class="invalid-feedback">
                      Please provide a valid Division.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="id_billing_zip">Zip Code</label>
                    {{ form.billing_zip }}
                    {% comment %} <input type="text" placeholder="Zip Code" id="billing_zip" name="billing_zip" class="form-control"> {% endcomment %}
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  {% comment %} <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing"> {% endcomment %}
                  {{ form.set_default_billing }}
                  <label class="custom-control-label" for="id_set_default_billing">Save the default shipping address</label>
                </div>
              </div>
            
              
              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                {% comment %} <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing"> {% endcomment %}
                {{ form.use_default_billing }}
                <label class="custom-control-label" for="id_use_default_billing">Use default billing address: {{ default_billing_address.secondary_addrs|truncatechars:20 }}</label>
              </div>
              {% endif %}

              <hr>
            </div>

              <h3>Payment Option</h3>
              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ value }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ value }}">{{ name }}</label>
                </div>
                {% endfor %}
                {% comment %} <div class="custom-control custom-radio">
                  <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="paypal">Paypal</label>
                </div> {% endcomment %}
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
        </div>

        <div class="col-md-4 mb-4">
          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">

          {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.item.title }} <b>x</b> ({{ order_item.quantity }})</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
              </div>
              <span class="text-muted">$ {{ order_item.get_final_price }}</span>
            </li>
            {% endfor %}

            {% if order.cupon %}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-danger">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.cupon.cupon }}</small>
              </div>
              <span class="text-danger">-${{order.cupon.amount}}</span>
            </li>
            {% endif %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$ {{order.get_total}}</strong>
            </li>
            
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          {% if order.cupon %}
            <form class="card p-2" action="{% url 'core:add-cupon' %}" method="POST">
              {% csrf_token %}
              <div class="input-group">
                {{ cuponform.cupon }}
                <div class="input-group-append">
                  <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
              </div>
            </form>
          {% endif %}
          <!-- Promo code -->
        </div>
      </div>
    </div>
  </main>

{% endblock content %}

{% block extra_scripts_for_checkout_form %}
<script>

var hidable_shipping_form = $('.hidable_shipping_form');
var hidable_billing_form = $('.hidable_billing_form');
var hidable_same_billing_form = $('.hidable_same_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");
var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var same_billing_address = document.querySelector("input[name=same_billing_address]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hidable_shipping_form.hide();
  } else {
    hidable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hidable_billing_form.hide();
  } else {
    hidable_billing_form.show();
  }
})

same_billing_address.addEventListener('change', function() {
  if (this.checked) {
    hidable_same_billing_form.hide();
  } else {
    hidable_same_billing_form.show();
  }
})

</script>
{% endblock extra_scripts_for_checkout_form %}

templates/item_list.html
{% extends './base.html' %}

{% block content %}
    <h4>Here are the all list of item</h4>
    {% for item in items %}
        {{item.title}}
    {% endfor %}

{% endblock content %}

templates/request_refund.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="main">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Request Refund</h3>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}